---
title: "R VecDyn template Markdown Script"
author: "Matthew J Watts"
date: "21 February 2018"
output: html_document
---

```{r}
Data_Series_Information_template <-data.frame(title=character(), 
                 collection_auth=character(), 
                 DOI=character(),
                 pub_date=as.Date(character()),
                 description=character(),
                 contact_name=character(),
                 auth_affiliation=character(),
                 auth_email=character(),
                 ORCID=character(),
                 keywords=character(),
                 stringsAsFactors=FALSE)
write.csv(Data_Series_Information_template, file = "Data_Series_Information_template.csv", row.names = FALSE)
```
                 

```{r}
VecDyn_template <-data.frame(data_set_name=character(), 
                             collection_start_datetime = as.Date(character()),
                             collection_end_datetime = as.Date(character()),
                             value =numeric(),
                             sample_info = character(),
                             sample_name = character(),
                             taxon_name = character(),
                             country = character(),
                             location_description = character(),
                             location_environment =character(),
                             study_lat_DD =double(),
                             study_long_DD =double(),
                             spatial_accuracy =numeric(),
                             location_extent =character(),
                             geo_datum =character(),
                             species_id_method =character(),
                             study_design =character(),
                             sampling_strategy =character(),
                             sampling_method =character(),
                             sampling_protocol =character(),
                             measurement_unit =character(),
                             sample_collection_area =character(),
                             value_transform =character(),
                             stringsAsFactors=FALSE)
write.csv(VecDyn_template, file = "VecDyn_template.csv", row.names = FALSE)
                             
```


